version: "3"

services:
    db:
        image: postgres 
        environment: 
            POSTGRES_PASSWORD: 123
            POSTGRES_USER: postgres
            POSTGRES_DB: app_db
        ports: 
            - "5432:5432"
        volumes: 
            - ~/.pgdata:/var/lib/postgresql/data